#!/bin/bash
set -euo pipefail

# ============================================================
# OneWeblog 部署脚本
# 适用于: Ubuntu 20.04+ / Debian 11+ (Tencent Cloud 轻量服务器)
# 用法:   chmod +x deploy.sh && sudo ./deploy.sh
#         （在项目根目录执行）
# ============================================================

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# -------------------- 配置 --------------------
DOMAIN="oneweblog.cn"
WWW_DOMAIN="www.oneweblog.cn"
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
NGINX_CONF="/etc/nginx/sites-available/oneweblog"
NODE_PORT="4321"

# -------------------- 权限检查 --------------------
[ "$EUID" -ne 0 ] && err "请用 sudo 运行此脚本"

# ============================================================
log "=== 第 1 步：系统依赖 ==="

apt-get update -qq

# Node.js 22.x LTS（Astro 7 要求 >=22.12.0）
if ! command -v node &>/dev/null; then
    log "安装 Node.js 22.x..."
    NODE_VERSION="22.20.0"
    NODE_ARCH="linux-x64"
    NODE_URL="https://npmmirror.com/mirrors/node/v${NODE_VERSION}/node-v${NODE_VERSION}-${NODE_ARCH}.tar.xz"

    curl -fsSL "$NODE_URL" -o /tmp/node.tar.xz
    tar -xJf /tmp/node.tar.xz -C /usr/local --strip-components=1
    rm -f /tmp/node.tar.xz
fi
log "Node.js $(node -v), npm $(npm -v)"

# Nginx
if ! command -v nginx &>/dev/null; then
    log "安装 Nginx..."
    apt-get install -y nginx
    systemctl enable nginx
fi
log "Nginx $(nginx -v 2>&1 | cut -d/ -f2)"

# PM2
if ! command -v pm2 &>/dev/null; then
    log "安装 PM2..."
    npm install -g pm2
fi

# Certbot (Let's Encrypt)
if ! command -v certbot &>/dev/null; then
    log "安装 Certbot..."
    apt-get install -y certbot python3-certbot-nginx
fi

# ============================================================
log "=== 第 2 步：安装依赖 & 构建 ==="

cd "$PROJECT_DIR"
[ -f "$PROJECT_DIR/package.json" ] || err "未找到 package.json，请在项目根目录运行此脚本"

# 使用阿里云镜像加速
log "使用阿里云 npm 镜像..."
npm config set registry https://registry.npmmirror.com

# Puppeteer 暂未使用，跳过浏览器下载
export PUPPETEER_SKIP_DOWNLOAD=true
rm -rf /root/.cache/puppeteer

npm install
npx astro build

log "构建完成"

# ============================================================
log "=== 第 3 步：启动 Node 服务 ==="

npx pm2 delete oneweblog 2>/dev/null || true
npx pm2 start npm --name oneweblog -- run start
npx pm2 save
npx pm2 startup systemd -u root --hp /root 2>/dev/null || true

log "Node 服务已启动 (端口 $NODE_PORT)"

# ============================================================
log "=== 第 4 步：Nginx 配置 ==="

cat > "$NGINX_CONF" << NGINX
# OneWeblog — generated by deploy.sh

server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN $WWW_DOMAIN;

    # 静态资源直接 serve（hash 文件名，长期缓存）
    location /_astro/ {
        root $PROJECT_DIR/dist/client;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # PDF / 下载文件直接 serve
    location /files/ {
        alias $PROJECT_DIR/public/files/;
        expires 7d;
        add_header Cache-Control "public";
    }

    # 其余请求反向代理到 Node
    location / {
        proxy_pass http://127.0.0.1:$NODE_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
    }

    # 安全头
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
NGINX

ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/oneweblog
rm -f /etc/nginx/sites-enabled/default

nginx -t && systemctl reload nginx
log "Nginx 配置已更新"

# ============================================================
log "=== 第 5 步：SSL 证书 ==="

if certbot certificates 2>/dev/null | grep -q "$DOMAIN"; then
    log "SSL 证书已存在，尝试续期..."
    certbot renew --quiet --nginx || true
else
    log "申请 SSL 证书..."
    certbot --nginx -d "$DOMAIN" -d "$WWW_DOMAIN" --non-interactive --agree-tos --email "admin@$DOMAIN" || {
        warn "证书申请失败，请稍后手动执行: sudo certbot --nginx -d $DOMAIN"
    }
fi

# ============================================================
log "=== 完成 ==="

echo ""
log "站点: https://$DOMAIN"
log "Node 端口: $NODE_PORT"
log "PM2 管理: pm2 status"
log "查看日志: pm2 logs oneweblog"
log ""
log "后续更新: ./scripts/update.sh"
log "新增文章: 直接 scp .mdx 文件到 src/content/，刷新页面即可"
echo ""

# 证书自动续期 cron
if ! crontab -l 2>/dev/null | grep -q 'certbot renew'; then
    (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet --nginx && systemctl reload nginx") | crontab -
fi
